spring:
  application:
    name: todo-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres # jdbc:h2:mem:security-security
    driverClassName: org.postgresql.Driver # org.h2.Driver
    username: postgres # root
    password: dv9899
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
token:
  signing:
    key: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855